spring:
  datasource:
    url: jdbc:h2:mem:library
  sql:
    init:
      mode: always
#  web:
#    resources:
#      chain:
#        strategy:
#          content:
#            enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false

logging:
  level:
    root: info
    org.springframework: info