DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255)

);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255),
    `YEAR` INT,
    AUTHOR_ID INT,
    GENRE_ID INT,
    foreign key (AUTHOR_ID) references AUTHORS(ID),
    foreign key (GENRE_ID) references GENRES(ID)
);