spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: books
  main:
    allow-bean-definition-overriding: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework.mongock.changelog
    - ru.otus.example.mongodbdemo.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local